name: Cotizador CI

# Ejecuta el flujo de trabajo en la rama main, cada que se haga un push o un pull request
# utilizando un entorno Ubuntu
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Obtiene una copia del repositorio
    - uses: actions/checkout@v4
      
    - name: Configura el JDK 17
      uses: actions/setup-java@v2 
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Da permisos de ejecución a gradlew
      run: chmod +x gradlew

    - name: Construye la aplicación con gradle
      run: ./gradlew build

    - name: Se inicia la aplicación
      run: ./gradlew bootRun &
      shell: bash
      
    - name: Realiza las pruebas
      run: ./gradlew test
