name: Cotizador CI

# Ejecuta el flujo de trabajo en la rama main, cada que se haga un push o un pull request
# utilizando un entorno Ubuntu
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      # Obtiene una copia del repositorio
    - uses: actions/checkout@v4
      
    - name: Instala el java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Configuración Gradle
      uses: gradle/gradle-build-action@v2

    - name: Compila el proyecto
      run: gradle build
